project:
  type: book
  output-dir: docs 

book:
  title: "Técnicas Experimentais em Agronomia" 
  output-file: "Apostila_TE" 
  author: 
    - name: "Inês Cristina de Batista Fonseca" 
    - name: "Guilherme Biz"
 
  chapters:
    - index.qmd 
    - intro.qmd
    - introducao.qmd
    - descritiva.qmd
    - va_tecnicas.qmd
    - Dist_amostrais.qmd
    - Estimacao_TE.qmd
    - TH_TE.qmd
    - references.qmd 
    

 
bibliography: references.bib
lang: pt 
language:
  toc-title: "Sumário" 

format:
  pdf:
    toc-title: "Sumário"
    include-in-header:
      text: |
        \addto\captionsportuguese{%
          \renewcommand{\contentsname}{Sumário}
        } 
        \usepackage{multirow}
        \usepackage{array}
        \usepackage{makecell}
        \usepackage{longtable}
        \usepackage{tikz}
        \usepackage{pdfpages}
        \usepackage{tablefootnote}

        
editor: visual

