# Plano de ensino

1.  **Identificação**

    **Disciplina:** Técnicas Experimentais em Agronomia (2AGR245)

    **Curso:** Pós-graduação em Agronomia

    **Ano Letivo:** 2026 - 1º Semestre - **Carga horária:** 120 horas ( 8 horas/semana)

    **Horário das Aulas**: 8h30 às 18h nas Quintas-feiras

    **Local**: Anfiteatro da Pós-Graduação do CCA

    **Professores:**

    -   Profª. Dr.ª Inês Cristina de Batista Fonseca - \texttt{inescbf@uel.br}

    <!-- -->

    -   Prof. Dr. Guilherme Biz - \texttt{gbiz@uel.br}

2.  **Ementa**

Estatística Descritiva. Distribuição Normal. Estimação. Teste de Hipóteses. Planejamento Estatístico de Experimentos em Agronomia. Análise de variância e testes de comparação de médias. Delineamentos experimentais em pesquisas em Agronomia. Regressão e Correlação.

3.  **Formas e critérios de Avaliação**

Duas avaliações sendo a média final por média aritmética simples.

4.  **Cronograma das Atividades**

\begin{longtable}{|p{1cm}|p{8.7cm}|p{5.5cm}|}
\hline
\multirow{2}{*}{\textbf{Dias}} & \multicolumn{2}{c|}{\textbf{Assunto}} \\ \cline{2-3}
 & \multicolumn{1}{c|}{\textbf{Manhã}} & \multicolumn{1}{c|}{\textbf{Tarde}} \\ \hline
\endfirsthead

\hline
\multirow{2}{*}{\textbf{Dias}} & \multicolumn{2}{c|}{\textbf{Assunto}} \\ \cline{2-3}
 & \multicolumn{1}{c|}{\textbf{Manhã}} & \multicolumn{1}{c|}{\textbf{Tarde}} \\ \hline
\endhead

\hline
\endfoot

\hline
\endlastfoot

\multirow{2}{*}{19/03} &
Apresentação da disciplina. Introdução à Estatística. Conceitos básicos e noções de amostragem.  &
Introdução ao software R e ao ambiente RStudio.  \\ \hline
\multirow{3}{*}{26/03} & Estatística Descritiva: construção e interpretação de tabelas e gráficos. Medidas descritivas de posição e dispersão. & Aplicações em Estatística Descritiva utilizando o software R. \\ \hline
\multirow{1}{*}{09/04} & Variáveis aleatórias contínuas e distribuição Normal. & Aplicações e uso do software R. \\ \hline
\multirow{2}{*}{16/04} & Introdução à Inferência Estatística: estimativas pontuais e intervalares. & Aplicações com o uso do software R.\\\hline
\multirow{2}{*}{23/04} &  Testes de hipóteses estatísticas: conceitos fundamentais, procedimentos e interpretação dos resultados.& Aplicações com o uso do software R.\\\hline
\multirow{3}{*}{30/04} & Avaliação sobre os conteúdos de introdução à Estatística, Estatística Descritiva, distribuição Normal, estimação e testes de hipóteses. &  \\\hline
\multirow{5}{*}{07/05} & Devolutiva e discussão da avaliação. Introdução ao Planejamento Estatístico de Experimentos Agronômicos.Delineamento Inteiramente Casualizado: modelo matemático, hipóteses básicas para a validade da ANOVA e obtenção da análise de variância.& Aplicações utilizando o software R.\\\hline
\multirow{2}{*}{14/05} & Aplicações do Delineamento Inteiramente Casualizado. Testes de comparações múltiplas.  & Uso do software R. \\\hline
\multirow{2}{*}{21/05} & Delineamento Casualizado em Blocos: conceitos, modelo estatístico e análise. & Aplicações com o uso do software R.\\\hline
\multirow{2}{*}{28/05} & Experimentos fatoriais com dois fatores: conceitos, modelagem estatística e análise de variância. & Uso do software R.\\\hline
\multirow{3}{*}{11/06} & Experimentos fatoriais com três ou mais fatores: modelagem estatística, análise e interpretação dos resultados. & Uso do software R.\\\hline
\multirow{2}{*}{18/06} & Experimentos em parcelas subdivididas: estrutura do delineamento, modelo estatístico e análise. & Uso do software R. \\\hline
\multirow{2}{*}{25/06} &  Análise de regressão utilizando polinômios ortogonais. & Aplicações com o uso do software R. \\\hline
\multirow{3}{*}{02/07} & Análise conjunta de grupos de experimentos. & Aplicações e interpretação dos resultados com o uso do software R.\\\hline
\multirow{2}{*}{09/07} & Avaliação sobre os conteúdos de Estatística Experimental.& \\\hline
\end{longtable}

5.  **Bibliografia**

ANDRADE, D. O.; OGLIARI, P. J. Estatística para as Ciências Agrárias e Biológicas: com Noções de Experimentação. 3ª ed. - Florianópolis: Ed da UFSC, 2017. 475p.

BANZATTO, D. A.; KRONKA, S. N. Experimentação Agrícola. 4. ed. Jaboticabal: FUNEP, 2013.

BARBIN, D. Planejamento e Análise Estatística de Experimentos Agronômicos. 2. ed. rev. ampl. - Londrina: Mecenas, 2013. 214p.

BUSSAB, W. O.; MORETTIN, P.A. Estatística Básica. 10ª ed. São Paulo: Saraiva, 2023. 624p.

FERREIRA, DANIEL F. Estatística Básica. 2ª ed. Lavras: Ed. UFLA, 2009.

FERREIRA, P.V. Estatística experimental aplicada à agronomia. 3ª ed. Maceió: EDUFAL, 2000. 419p.

FONSECA, J.S.; MARTINS, G.A. Curso de estatística. 6ª ed. São Paulo: Atlas, 1996. 320p.

GOMES, F. P. Curso de Estatística Experimental. 15. ed. Piracicaba: FEALQ, 2009.

MONTGOMERY, D. C.; RUNGER, G. C. Estatística Aplicada e Probabilidade para Engenheiros. 7. ed. Rio de Janeiro: LTC, 2024.

MORETTIN, P.A.; BUSSAB, W. O. Estatística Básica. 10. ed. São Paulo: SaraivaUni, 2023.

VIEIRA, S.; HOFFMANN, R. Estatística Experimental. São Paulo: Atlas, 1999.
